Don't touch files if they don't need changing
serokell/nixfmt pull request #133
Opened 2023-09-25 15:34 UTC by piegamesde

Fixes #88

This has not been tested yet, CC @SebTM please take a look

2023-09-26 00:18 UTC, SebTM commented
Thanks very much for looking into this as fast as you did 🚀 
Works well, tested it as following:

Modified mtime of flake.nix via `touch -mt 0911171533 flake.nix` and ran new build of nixfmt:
```
-rw-r--r-- 1 sebtm users  3330 Nov 17  2009 flake.nix
dist-newstyle/build/x86_64-linux/ghc-9.0.2/nixfmt-0.5.0/x/nixfmt/build/nixfmt/nixfmt flake.nix
-rw-r--r-- 1 sebtm users  3330 Nov 17  2009 flake.nix
```

running afterwards my old install of nixfmt results in:
```
-rw-r--r-- 1 sebtm users  3330 Nov 17  2009 flake.nix
nixfmt flake.nix
-rw-r--r-- 1 sebtm users  3330 Sep 26 02:15 flake.nix
```

which demonstrates the difference again :) so LGTM

2023-09-26 19:02 UTC, infinisil requested changes

2023-09-26 19:07 UTC, infinisil commented on main/Main.hs
> +    mapM (\formatted -> tDoWrite (formatted /= contents) formatted) formatResult
Seems like this might not work after discussing with @piegamesde in the call :)

2023-09-27 06:17 UTC, SebTM commented on main/Main.hs
> +    mapM (\formatted -> tDoWrite (formatted /= contents) formatted) formatResult
Just let me know if I can test again 🥳

2023-10-02 09:50 UTC, infinisil approved these changes

2023-10-02 09:52 UTC, infinisil commented on CHANGELOG.md
> +* Fix treefmt compatibility
```suggestion
* Don't write if files didn't change, fixing treefmt compatibility
```

2023-10-04 17:31 UTC, Lucus16 approved these changes

2023-10-04 18:19 UTC, infinisil commented
I'd merge, but can't because CI doesn't seem to run

2023-10-04 18:28 UTC, piegamesde commented
CI doesn't seem to be running, I have no idea what's happening there. I could probably manually merge and push to master, but that would be undesirable. The CI is broken in #132 too btw

2023-10-05 08:29 UTC, Lucus16 commented
We'll need to get #134 merged for CI to work. If you don't want to wait for it, just run CI locally and then merge to master manually.

2023-10-09 19:09 UTC, merged