Convert this project to use Nix flakes
serokell/nixfmt pull request #75
Opened 2020-11-29 21:45 UTC by notgne2

2020-11-30 08:12 UTC, zhenyavinogradov requested changes
There are errors in CI, pipeline steps need to be updated as well. Other than that, looks good

2020-11-30 17:13 UTC, notgne2 commented
https://hydra.nixos.org/build/129701778 😠

2021-12-01 11:59 UTC, Lucus16 commented
I'm okay with adding support for flakes but I want nixfmt to continue to be usable without using flakes so please don't remove or significantly change the existing Nix files.

2021-12-05 07:45 UTC, SuperSandro2000 commented
> to continue to be usable without using flakes

This is what flake-compat does. You don't need to have flakes enabled for it.

2021-12-05 08:36 UTC, 0x4A6F commented on flake.nix
> +  description = "A Simple multi-profile Nix-flake deploy tool.";
Looks like copypasta from deploy-rs, could use a better description:  A formatter for Nix code

2022-02-25 13:13 UTC, merged